{
  "context": "",
  "datetime": "2025-03-20T10:48:00.454849",
  "stack_trace": "Traceback (most recent call last):\n  File \"/home/phi/PROJECTS/geometor/seer/src/geometor/seer/seer.py\", line 58, in solve\n    self._investigate(task, session_task)\n    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"/home/phi/PROJECTS/geometor/seer/src/geometor/seer/seer.py\", line 118, in _investigate\n    task_step.summarize()\n    ~~~~~~~~~~~~~~~~~~~^^\n  File \"/home/phi/PROJECTS/geometor/seer/src/geometor/seer/session/task_step.py\", line 91, in summarize\n    all_train_results.extend(code_trial.train_results.get(\"trials\", []))\n                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'list' object has no attribute 'get'\n",
  "exception": "'list' object has no attribute 'get'"
}