
ERROR

Error during summarization of TaskStep: investigate • coder • all training
'GenerateContentResponse' object has no attribute 'get'
Traceback (most recent call last):
  File "/home/phi/PROJECTS/geometor/seer/src/geometor/seer/session/task_step.py", line 85, in summarize
    retries_count = self.response.get("retries", None)
                    ^^^^^^^^^^^^^^^^^
AttributeError: 'GenerateContentResponse' object has no attribute 'get'

