[2025-02-27T07:31:23.537750] ERROR: 'str' object has no attribute 'get'
Traceback (most recent call last):
  File "/home/phi/PROJECTS/geometor/seer/src/geometor/seer/seer.py", line 95, in solve
    self._investigate(task)
    ~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/phi/PROJECTS/geometor/seer/src/geometor/seer/seer.py", line 178, in _investigate
    self._test_extracted_codelist(extracted_code_list, task)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/phi/PROJECTS/geometor/seer/src/geometor/seer/seer.py", line 235, in _test_extracted_codelist
    all_test_passed = all(
        result.get("match") is True
        for result in current_test_results
    )  # Use current_test_results
  File "/home/phi/PROJECTS/geometor/seer/src/geometor/seer/seer.py", line 236, in <genexpr>
    result.get("match") is True
    ^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'


