{
  "context": "Error during summarization of TaskStep: refine \u2022 0 \u2022 coder",
  "datetime": "2025-04-05T12:01:45.237885",
  "stack_trace": "Traceback (most recent call last):\n  File \"/home/phi/PROJECTS/geometor/seer/src/geometor/seer/session/task_step.py\", line 110, in summarize\n    trial_analysis = StepCodeTrials.analyze_trial_data(trial_data_list)\n  File \"/home/phi/PROJECTS/geometor/seer/src/geometor/seer/trials/step_code_trials.py\", line 169, in analyze_trial_data\n    test_pair_trials = test_results_data.get(TRIALS_LIST_KEY, [])\n                       ^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'NoneType' object has no attribute 'get'\n",
  "exception": "'NoneType' object has no attribute 'get'"
}