{
  "context": "",
  "datetime": "2025-03-25T10:05:35.766351",
  "stack_trace": "Traceback (most recent call last):\n  File \"/home/phi/PROJECTS/geometor/seer/src/geometor/seer/seer.py\", line 54, in solve\n    self._investigate(task, session_task)\n    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"/home/phi/PROJECTS/geometor/seer/src/geometor/seer/seer.py\", line 137, in _investigate\n    task_step = self.refine(\n        session_task,\n    ...<3 lines>...\n        current_iteration,\n    )\n  File \"/home/phi/PROJECTS/geometor/seer/src/geometor/seer/seer.py\", line 205, in refine\n    task_step = self._generate(\n        session_task,\n    ...<5 lines>...\n        tools=\"code_execution\"  # Consider if tools are needed\n    )\n  File \"/home/phi/PROJECTS/geometor/seer/src/geometor/seer/seer.py\", line 178, in _generate\n    task_step.log_response(response, response_time)\n    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/phi/PROJECTS/geometor/seer/src/geometor/seer/session/task_step.py\", line 151, in log_response\n    self.log_markdown(\"response\", [response.text])\n                                   ^^^^^^^^^^^^^\n  File \"/home/phi/.pyenv/versions/3.13.2/lib/python3.13/site-packages/google/generativeai/types/generation_types.py\", line 463, in text\n    parts = self.parts\n            ^^^^^^^^^^\n  File \"/home/phi/.pyenv/versions/3.13.2/lib/python3.13/site-packages/google/generativeai/types/generation_types.py\", line 446, in parts\n    raise ValueError(msg)\nValueError: Invalid operation: The `response.parts` quick accessor requires a single candidate, but but `response.candidates` is empty.\n",
  "exception": "Invalid operation: The `response.parts` quick accessor requires a single candidate, but but `response.candidates` is empty."
}