{
  "context": "Error writing to json: ../sessions/25.079.0642/6150a2bd/001/code_00.py.trial.json",
  "datetime": "2025-03-20T06:43:15.336350",
  "stack_trace": "Traceback (most recent call last):\n  File \"/home/phi/PROJECTS/geometor/seer/src/geometor/seer/session/task_step.py\", line 209, in _write_to_json\n    json.dump(content, f, indent=2)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/phi/.pyenv/versions/3.13.2/lib/python3.13/json/__init__.py\", line 179, in dump\n    for chunk in iterable:\n                 ^^^^^^^^\n  File \"/home/phi/.pyenv/versions/3.13.2/lib/python3.13/json/encoder.py\", line 439, in _iterencode\n    o = _default(o)\n  File \"/home/phi/.pyenv/versions/3.13.2/lib/python3.13/json/encoder.py\", line 180, in default\n    raise TypeError(f'Object of type {o.__class__.__name__} '\n                    f'is not JSON serializable')\nTypeError: Object of type CodeTrial is not JSON serializable\n",
  "exception": "Object of type CodeTrial is not JSON serializable"
}